# Generated by Django 3.2.8 on 2021-10-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_refactor_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zillowlisting',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zillow_listing', to='api.house'),
        ),
    ]
